language: java
jdk:
  - openjdk7

before_install: git clone https://github.com/BuildCraft/BuildCraft-Localization.git ../BuildCraft-Localization
install: ./gradlew setupCIWorkspace -S
script: ./gradlew build
after_success: - .utility/initiate-publish.sh

env:
  global:
    TERM=dumb
    